server:
  port: 878

spring:
  application:
    name: mail_demo
  config:
    import: custom/application-dev-custom.yml
  mail:
    host: smtp.163.com
    port: 465
    username: xxx@163.com
    # 授权码
    password: xxx
    properties:
      mail:
        smtp:
          # 如果是用 SSL 方式, 需要配置如下属性
          ssl:
            enable: true
            required: true
          timeout: 10000
          connectiontimeout: 10000
          writetimeout: 10000
        debug: true